name: Check app
on: push
jobs:
  testing:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Run Karma tests
        run: npm run test
  linting:
    runs-on: ubuntu-20.04
    needs: testing
    steps:
      - name: Enable npx
        uses: mikeal/npx@1.0.0
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Check linting on errors
        run: npx prettier --loglevel error --check .
