name: Check app
on: push
jobs:
  testing:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Run Karma tests
        run: npm run test
  linting:
    runs-on: ubuntu-20.04
    needs: testing
    steps:
      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Check linting on errors
        run: npx prettier --loglevel error --check .
