name: Pull request
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - edited
      - reopened

jobs:
  print:
    runs-on: ubuntu-20.04
    steps:
      - name: Print context
        run: echo "${{ toJson(github.event) }}"
